export const SET_SUPPLY_LIST = 'SET_SUPPLY_LIST'
export const SET_DEMAND_LIST = 'SET_DEMAND_LIST'
export const SET_DEMAND_ITEM = 'SET_DEMAND_ITEM'

export const SET_LOADING = 'SET_LOADING'
export const SET_TARGET_VAL = 'SET_TARGET_VAL'
export const SET_QUERY_KEYWORD = 'SET_QUERY_KEYWORD'